//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamchatkaSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryTable()
        {
            this.ServiceTable = new HashSet<ServiceTable>();
        }
    
        public long CategoryID { get; set; }
        public long SeasonID { get; set; }
        public string CategoryNameRus { get; set; }
        public string CategoryNameCh { get; set; }
        public string CategoryDescriptionRus { get; set; }
        public string CategoryDescriptionCh { get; set; }
        public string CategoryPicture { get; set; }
        public string CategoryUrlName { get; set; }
    
        public virtual SeasonTable SeasonTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceTable> ServiceTable { get; set; }
    }
}
