//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamchatkaSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KmTableEntities : DbContext
    {
        public KmTableEntities()
            : base("name=KmTableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTable> CategoryTable { get; set; }
        public virtual DbSet<SeasonTable> SeasonTable { get; set; }
        public virtual DbSet<ServiceImagesTable> ServiceImagesTable { get; set; }
        public virtual DbSet<ServiceTable> ServiceTable { get; set; }
    }
}
