//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamchatkaSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeasonTable()
        {
            this.CategoryTable = new HashSet<CategoryTable>();
        }
    
        public long SeasonID { get; set; }
        public string SeasonNameRus { get; set; }
        public string SeasonNameCh { get; set; }
        public string SeasonDescriptionRus { get; set; }
        public string SeasonDescriptionCh { get; set; }
        public string SeasonUrlName { get; set; }
        public string SeasonMainImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryTable> CategoryTable { get; set; }
    }
}
