//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamchatkaSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceImagesTable
    {
        public long ImageID { get; set; }
        public long ServiceID { get; set; }
        public string ImageSrc { get; set; }
    
        public virtual ServiceTable ServiceTable { get; set; }
    }
}
